default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: safe_delete_development
  host: localhost
  username: postgres
  password: root

test:
  <<: *default
  database: safe_delete_test
  host: localhost
  username: postgres
  password: root
#
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
